### ISSUE TITLE
Can not build the sample

### ISSUE THREAD

**Issue by anhchangchoai** [AppsFlyerSDK/Unity#1]
The error : 
"Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
C:\DevTools\ADT\sdk\build-tools\android-4.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I "C:/DevTools/ADT/sdk/platforms/android-19\android.jar" -F bin/resources.ap_

stderr[
invalid resource directory name: res/version.xml
]
stdout[

]" 
would be showed when I build the sample
Could any one fix this bug?

**Comment by chiciubogdan** [comment]
This still happens when trying to integrate the plugin.

**Comment by cviedmai** [comment]
Try putting the xml file in /res/values/version.xml instead.
According to Google's documentation the definition of integers must be in /res/values/
http://developer.android.com/guide/topics/resources/more-resources.html#Integer
