### ISSUE TITLE
EntryPointNotFoundException: mSetAppsFlyerDevKey

### ISSUE THREAD

**Issue by jpatinop** [AppsFlyerSDK/Unity#11]
I got this error on unity 5.2.2 
EntryPointNotFoundException: mSetAppsFlyerDevKey
AppsFlyer.setAppsFlyerKey (System.String key) (at Assets/Plugins/AppsFlyer.cs:63)
StartUp.Start () (at Assets/StartUp.cs:9)

**Comment by papatriz** [comment]
Same issue. 
Got this in Unity editor. Works fine on devices.
Also doesn't stop execution in editor, so this is not a big problem.

**Comment by malarkannaninvention** [comment]
issue is unity preprocesor issue i guess, 
if you prepend 

    #if UNITY_EDITOR
	public static void trackEvent(string eventName,string eventValue){}
	public static void setCurrencyCode(string currencyCode){}
	public static void setCustomerUserID(string customerUserID){}
	public static void loadConversionData(string callbackObject,string callbackMethod){}
	public static void setAppsFlyerKey(string key){}
	public static void trackAppLaunch(){}
	public static void setAppID(string appleAppId){}
	public static void trackRichEvent(string eventName, Dictionary<string, string> eventValues){}
	public static void validateReceipt(string productIdentifier, string price, string currency){}
	public static void setIsDebug(bool isDebug){}
	public static void setIsSandbox(bool isSandbox){}
	public static void getConversionData (){}
	public static string getAppsFlyerId () {return null;}
	public static void handleOpenUrl(string url, string sourceApplication, string annotation) {}

	#elif UNITY_IOS

and delete the #else part it works fine.
