### ISSUE TITLE
NoSuchMethodError with validateAndTrackInAppPurchase

### ISSUE THREAD

**Issue by bryanfiles** [AppsFlyerSDK/Unity#12]
With the package from Novermber 10th, I get this error when test IAP validation on Android:

AndroidJavaException: java.lang.NoSuchMethodError: no static method "Lcom/appsflyer/AppsFlyerLib;.validateAndTrackInAppPurchase(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V"

**Comment by golan19** [comment]
Issues fixed... please update.
