### ISSUE TITLE
Issue accessing com.appsflyer.AppsFlyerUnityHelper

### ISSUE THREAD

**Issue by dcompton** [AppsFlyerSDK/Unity#13]
Greetings, I have downloaded Master (commit 96ff31437e59910e54f05e7b0b57dc6812344ba9 - 70ee068411303ff659f9ca35600eba18beb2841d works btw) with Unity version 5.2.2f1. I then followed the guide to add the plugin to the application, i.e. I can see your .java in the Android/com/ directory and the AF-Android-SDK.jar and AppsFlyerAndroidPlugin.jar are both present. Upon calling the AppsFlyer Class for the first time: 

AppsFlyer.setAppsFlyerKey (<my key>); 

the following error is thrown: 

12-01 18:42:28.408 I/Unity   ( 2513): AndroidJavaException: java.lang.ClassNotFoundException: com.appsflyer.AppsFlyerUnityHelper
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513):   at AppsFlyer..cctor () [0x00000] in <filename unknown>:0 
12-01 18:42:28.408 I/Unity   ( 2513): Rethrow as TypeInitializ

the call to creation of com.appsflyer.AppsFlyerLib works fine. Trying to create the helper fails.

**Comment by golan19** [comment]
please get the latest.. thanks.
