### ISSUE TITLE
java.lang.ClassNotFoundException: Cannot find class: com.appsflyer.AppsFlyerUnityHelper$2.class

### ISSUE THREAD

**Issue by fengwlmo** [AppsFlyerSDK/Unity#15]
java.lang.ClassNotFoundException: Cannot find class: com.appsflyer.AppsFlyerHelper$2.class.
it' occurred when running on android device. it's look like have no class file named AppsFlyerUnityHelper$2.class in the AppsFlyerAndroidPlugin.jar.
what's wrong?

**Comment by golan19** [comment]
please update
