### ISSUE TITLE
Example crash

### ISSUE THREAD

**Issue by whylieme1** [AppsFlyerSDK/Unity#16]
hi, i have do follow guide and build an example app for testing trackAppLaunch but i got this error on Unity: 

Exception: JNI: Init'd AndroidJavaClass with null ptr!
UnityEngine.AndroidJavaClass..ctor (IntPtr jclass) (at C:/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:539)
UnityEngine.AndroidJavaObject.get_JavaLangClass () (at C:/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:517)
UnityEngine.AndroidJavaObject.FindClass (System.String name) (at C:/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:508)
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) (at C:/buildslave/unity/build/Runtime/Export/AndroidJavaImpl.cs:528)
UnityEngine.AndroidJavaClass..ctor (System.String className) (at C:/buildslave/unity/build/artifacts/EditorGenerated/AndroidJava.cs:93)
AppsFlyer..cctor ()
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for AppsFlyer
StartUp.Start () (at Assets/Plugins/StartUp.cs:9)
 And when i build this project to an android app, then run it on my device. It has crash. 
I added dev key on Androidmanifest.xml like this: 

    -->

    <meta-data android:name="AppsFlyerDevKey" android:value="KGjX4wCxDrueiJ7mRMjn6b"/>

  </application>
And here is my void Start :

	void Start () {

        AppsFlyer.setAppsFlyerKey("KGjX4wCxDrueiJ7mRMjn6b");

		#if UNITY_IOS 

		AppsFlyer.setAppID ("YOUR_APPLE_APP_ID_HERE");
		AppsFlyer.setIsDebug (true);
		AppsFlyer.getConversionData ();
		AppsFlyer.trackAppLaunch ();

		#elif UNITY_ANDROID

		// All Initialization occur in the override activity defined in the mainfest.xml, including track app launch
		// You can define AppsFlyer library here use this commented out code.

		// un-comment this in case you are not working with the android manifest file
		//AppsFlyer.setAppID ("YOUR_ANDROID_PACKAGE_NAME_HERE"); 

		// for getting the conversion data
		//AppsFlyer.loadConversionData("AppsFlyerTrackerCallbacks","didReceiveConversionData", "didReceiveConversionDataWithError");

		// for in app billing validation
		//AppsFlyer.createValidateInAppListener ("AppsFlyerTrackerCallbacks", "onInAppBillingSuccess", "onInAppBillingFailure"); 

		AppsFlyer.trackAppLaunch ();
		#endif

		print ("AppsFlyerId = " + AppsFlyer.getAppsFlyerId());

	}

Please help me !. Sorry for my bad english.

**Comment by infosekr** [comment]
I'm getting the same error, seems like the AppsFlyer C# code is unable to construct the java class files from the .jar, but the .jar are in the correct folder. Did you find a workaround for this?
