### ISSUE TITLE
Please follow a respectful directory structure so AppsFlyer code can be separated from other plugins

### ISSUE THREAD

**Issue by infosekr** [AppsFlyerSDK/Unity#17]
Please do not include loose files in the root folder of the project or the Plugins folder. This is messy and  pollutes existing project folders, and conflicts with existing files.

- Please place any AppsFlyer files in the root folder into a AppsFlyer folder
- Please place any Plugins/ files in a subfolder called Plugins/AppsFlyer/
- Please place any Plugins/<platform> files in a subfolder called Plugins/<platform>/AppsFlyer
- Do not include a Plugins/Android/AndroidManifest.xml as this conflicts with the existing manifest file, instead provide a Plugins/Android/AppsFlyer/Manifest.xml which will be automatically merged with the existing manifest file.

**Comment by AppsFlyerGit** [comment]
Done.
