### ISSUE TITLE
Exception on calling trackEvent(string,string) variant on Android

### ISSUE THREAD

**Issue by shilp-gupta** [AppsFlyerSDK/Unity#20]
I assume this method is deprecated. The android AppsFlyerLib clearly does not accept two strings. This is the exception I get

AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Lcom/appsflyer/AppsFlyerLib;.trackEvent(Lcom.unity3d.player.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;)V"

when I call

AppsFlyer.trackEvent("test_event","test_value")

**Comment by P1CACHU** [comment]
Same problem. Someone found solution? Should I use trackRichEvent instead trackEvent?

**Comment by shilp-gupta** [comment]
@P1CACHU Thats what I did. I use trackRichEvent with a string event name and an empty dictionary. I can see the events in my appsflyer dashboard.

**Comment by golan19** [comment]
Thanks @shilp-gupta, indeed the trackEvent (String, String) is no longer supported.
Please user TrackRichEvent instead.
