### ISSUE TITLE
java.lang.NoSuchMethodError Exception

### ISSUE THREAD

**Issue by SamiSdd** [AppsFlyerSDK/Unity#22]
I/Unity   ( 7713): AndroidJavaException: java.lang.NoSuchMethodError: no method
with name='createConversionDataListener' signature='(Lcom.prime31.UnityPlayerNat
iveActivity;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V' in class L
com/appsflyer/AppsFlyerUnityHelper;
I/Unity   ( 7713): java.lang.NoSuchMethodError: no method with name='createConve
rsionDataListener' signature='(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang
/String;Ljava/lang/String;Ljava/lang/String;)V' in class Lcom/appsflyer/AppsFlye
rUnityHelper;
I/Unity   ( 7713):      at com.unity3d.player.UnityPlayer.nativeRender(Native Me
thod)
I/Unity   ( 7713):      at com.unity3d.player.UnityPlayer.a(Unknown Source)
I/Unity   ( 7713):      at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
I/Unity   ( 7713):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] i
n <filename unknown>:0
I/Unity   ( 7713):   at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, Syst
em.String name, System.String sig) [0x00000] in <filename unknown>:0
I/Unity   ( 7713):   at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass
, System.String methodName, System.String signature, Boolean isStatic) [0x00000]

**Comment by SamiSdd** [comment]
Fixed myself.

https://github.com/SamiSdd/Unity/commit/73d9dc2a7604d2e0f561a11e336480113c934b25

**Comment by Sudarmin** [comment]
I have the same problem, can you share how to fix this?

**Comment by maksimonishchenko** [comment]
share a fix

**Comment by golan19** [comment]
Fixed..
