### ISSUE TITLE
Reporting Deeplinks for Re-Targeting Attribution

### ISSUE THREAD

**Issue by jay-neb** [AppsFlyerSDK/Unity#23]
Hey there,

Looking at the [SDK integration guide for iOS](https://support.appsflyer.com/hc/en-us/articles/207032066-iOS-SDK-Integration-Guide-v3-3-x-New-API-), point 5.7 shows how to report deep links to analyse the performance of re-targeting attribution campaigns. But it seems like I can't do this from the Unity plugin. Any ideas?

Thanks!

Jay

**Comment by hex** [comment]
I am also interested in this.

**Comment by af-golan** [comment]
Added deep linking to Unity
