### ISSUE TITLE
Error OBJC_CLASS

### ISSUE THREAD

**Issue by Sudarmin** [AppsFlyerSDK/Unity#24]
I got this error when I'm building my app on XCode : 

Build target Unity-iPhone of project Unity-iPhone with configuration Release

**_Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_AppsFlyerTracker", referenced from:
      objc-class-ref in AppsFlyerWrapper.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)_**

Anyone know how to fix this?

**Comment by af-golan** [comment]
Fixed
