### ISSUE TITLE
no visible @interface for 'AppsFlyerTracker' declares the selector 'handleOpenURL:sourceApplication:withAnnotaion:'

### ISSUE THREAD

**Issue by redsend** [AppsFlyerSDK/Unity#25]
I got this error in xCode

**Libraries/Plugins/iOS/AppsFlyerWrapper.mm:169:43**: error: no visible @interface for 'AppsFlyerTracker' declares the selector 'handleOpenURL:sourceApplication:withAnnotaion:'
        [[AppsFlyerTracker sharedTracker] handleOpenURL:[NSURL URLWithString:[NSString stringWithUTF8String:url]] sourceApplication:[NSString stringWithUTF8String:sourceApplication] withAnnotaion:[NSString stringWithUTF8String:annotation]];
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by Oxytocin** [comment]
The typo is the problem. There should be `withAnnotation`, but is: `withAnnotaion`.
