### ISSUE TITLE
Unity Build XCode Error

### ISSUE THREAD

**Issue by pranavt7** [AppsFlyerSDK/Unity#26]
/Users/SpielMini/Desktop/GalaxyRun2/Libraries/Plugins/iOS/AppsFlyerWrapper.mm:187:43: No visible @interface for 'AppsFlyerTracker' declares the selector 'handlePushNotification:'

I am getting this error, when I make an iOS build and try to run it. I added the framework and library. I wasn't sure where to write the "#import "AppsFlyerTracker.h" since it is a Unity build.

Any solutions for this?
Thank you

**Comment by Oxytocin** [comment]
The typo is the problem. There should be `withAnnotation`, but is: `withAnnotaion`.

**Comment by golan19** [comment]
Thanks guys, fixed the the typo.
