### ISSUE TITLE
Crash on android trackEvent

### ISSUE THREAD

**Issue by SamiSdd** [AppsFlyerSDK/Unity#29]
I/Unity (12600): AndroidJavaException: java.lang.NoSuchMethodError: no method with name='trackEvent' signature='(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;)V' in class Lcom/appsflyer/AppsFlyerLib;
I/Unity (12600): java.lang.NoSuchMethodError: no method with name='trackEvent' signature='(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;)V' in class Lcom/appsflyer/AppsFlyerLib;
I/Unity (12600): at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
I/Unity (12600): at com.unity3d.player.UnityPlayer.a(Unknown Source)
I/Unity (12600): at com.unity3d.player.UnityPlayer$b.run(Unknown Source)
I/Unity (12600): at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in :0 
I/Unity (12600): at UnityEngine.AndroidJNISafe.GetMethodID (IntPtr obj, System.String name, System.String sig) [0x00000] in :0 
I/Unity (12600): at UnityEngine._AndroidJNIHelper.GetMethodID (IntPtr jclass, System.String methodName, System.String signature, Boolean isStatic) [0x00000] in :0 
I/Unity (12600): at UnityEngine.AndroidJNIHelper.GetMethodID (IntPtr javaClass

name='trackEvent' signature='(Lcom.prime31.UnityPlayerNativeActivity;Ljava/lang/String;Ljava/lang/String;) the function getting called with trackEvent(Context, string, string) but the jar file seems to have **void trackEvent(Context paramContext, String paramString, Map<String, Object> paramMap)**

**Comment by golan19** [comment]
@SamiSdd. 
We will issue a fix for that, can you try calling instead,

public static void trackRichEvent(string eventName, Dictionary<string, string> eventValues)
