### ISSUE TITLE
cannot get the loadConversionData to work

### ISSUE THREAD

**Issue by Waoetfi** [AppsFlyerSDK/Unity#3]
I implemented it as the example shows but I never recieve any callbacks with the data any ideas what I might be doing wrong?
I implemented it in C# .
callback function:

public void HandleAppFlyerData(string json)
{
		Debug.Log ("Some data: " + json );
}

call for the calback registration:

AppsFlyer.loadConversionData(this.name, "HandleAppFlyerData");

the game object to which I attached thes script is never destroyed(I have some singeltons on it which are used trought the game).
According to logs AppsFlyer seems to be set up properly I get some Start tracking logs and launch logs event are sent properly as well ust cant get the callback to work.
Thanks for any advice.

**Comment by golan19** [comment]
Fixed, get the latest.
