### ISSUE TITLE
Unity-iOS : Background urlsession crashes the app

### ISSUE THREAD

**Issue by RegisUplike** [AppsFlyerSDK/Unity#30]
Hi,
My app crashes in background and it seems that the AppsFlyer plugin is the cause.
It happens when the network is bad. Here the crash log (I use the 4.3.9 version) :

Exception Type:  00000020
Exception Codes: 0x000000008badf00d
Exception Note:  SIMULATED (this is NOT a crash)
Highlighted by Thread:  7

Application Specific Information:
<BKNewProcess: 0x17e3c4c0; MyApp; pid: 7559; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x17e217f0> id: 110-C4ED3688-5ECD-4311-BD9E-F50B97CEC0B7 name: com.apple.nsurlsessiond.handlesession com.appsflyer.sdk process: <BKNewProcess: 0x17e3c4c0; MyApp; pid: 7559; hostpid: -1> permittedBackgroundDuration: 30.000000 reason: backgroundDownload owner pid:110 preventSuspend  preventThrottleDownUI  preventIdleSleep  preventSuspendOnSleep 
)}

**Comment by RegisUplike** [comment]
This bug seems to be fixed in the 4.1.1 version of the iOS framework.
When do you plan to update the Unity plugin?

Thank you.

**Comment by AppsFlyerGit** [comment]
Yes it is fixed, we will update Unity by the end of next week.
