### ISSUE TITLE
require security framework

### ISSUE THREAD

**Issue by jlGauthier** [AppsFlyerSDK/Unity#32]
The ios plugin uses the security framework but does not ask unity to include it. This can be fixed by checking the security framework in the inspector.

![screen shot 2016-05-04 at 5 11 24 pm](https://cloud.githubusercontent.com/assets/8954643/15029385/4b6e0842-121b-11e6-88f4-919509c4bece.png)

If the  security framework is not included xcode will produce errors like Undefined symbols for architecture arm64: _SecItemUpdate until the security framework is added.

**Comment by AppsFlyerGit** [comment]
Added Security FW
