### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by saehyun** [AppsFlyerSDK/Unity#34]
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method "Lcom/appsflyer/AppsFlyerLib;.init(Lcom.unity3d.player.UnityPlayerActivity;Ljava/lang/String;)V"
    java.lang.NoSuchMethodError: no non-static method "Lcom/appsflyer/AppsFlyerLib;.init(Lcom.unity3d.player.UnityPlayerActivity;Ljava/lang/String;)V"

Hi, I'm tried to run the example on Unity + Android. But I got this error.
How can I fix it?

**Comment by tengfeingoo** [comment]
Having the same issue here, but with our own project. It was working fine for a week or so, then this error started showing up more an more often.

**Comment by AppsFlyerGit** [comment]
@saehyun we should update the example.
@tengfeingoo Can you submit a ticket to support@appsflyer.com?
