### ISSUE TITLE
Crash in AppsFlyerDelegate.init under iOS7 and lower

### ISSUE THREAD

**Issue by nonnname** [AppsFlyerSDK/Unity#35]
Look at AppsFlyerDelegate.init method.
UIApplicationLaunchOptionsUserActivityDictionaryKey available only from ios 8 and above. 

Reproduce:
- Call AppsFlyer.getConversionData() in app launched under ios 7

**Comment by peony3d** [comment]
me too

**Comment by AppsFlyerGit** [comment]
@nonnname Thanks for the info. we are checking this and release a fix for that.
