### ISSUE TITLE
No additionalParametes in validateReceipt for Android

### ISSUE THREAD

**Issue by ArsenyLebedev** [AppsFlyerSDK/Unity#36]
Hello Dear team, 

Thank you for adding the validation option for Android as well, as it is very vital to verify the in-game purchases due to the great number of fraud activity we see there. But unfortunately we are not able to use it in full due to the lack of options that are available for Unity. We need the opportunity to customize the parameters of the Purchase event, but when using the validation request, the af_purchase event is generated automatically with the full list of parameters. The customised list of parameters that we are ready to pass is available only for iOS. As for Android in the file AppsFlyer.cs function validateReceipt does not contain the field Dictionary<string,string> additionalParametes. 

Is there any chances for us to costumize the  Purchase event parameters? 

Really looking forward to hearing from you.

Best,
Arseny

**Comment by AppsFlyerGit** [comment]
Added additionalParametes
