### ISSUE TITLE
java.lang.ClassNotFoundException: com.appsflyer.AppsFlyerLib

### ISSUE THREAD

**Issue by andrewsaputra** [AppsFlyerSDK/Unity#37]
Tried it in an empty project containing only AppsFlyer SDK (v4.8) in Unity 4.6.9

> I/Unity   (21192): AndroidJavaException: java.lang.ClassNotFoundException: com.appsflyer.AppsFlyerLib
I/Unity   (21192):   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <filename unknown>:0
I/Unity   (21192):   at UnityEngine.AndroidJNISafe.CallStaticObjectMethod (IntPtr clazz, IntPtr methodID, UnityEngine.jvalue[] args) [0x00000] in <filename unknown>:0
I/Unity   (21192):   at UnityEngine.AndroidJavaObject._CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
I/Unity   (21192):   at UnityEngine.AndroidJavaObject.CallStatic[AndroidJavaObject] (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0
I/Unity   (21192):   at UnityEngine.AndroidJavaObject.FindClass (System.String name) [0x00000] in <filename unknown>:0
I/Unity   (21192):   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className) [0x00000] in <filename unknown>:0
I/Unity   (21192):   at UnityEngine.AndroidJavaClass..ctor (System.String className) [0x00000] in <filename unknown>:0
I/Unity   (21192):   at AppsFlyer..cctor () [0x00000] in <filename unknown>:0
I/Unity   (21192): Rethrow as TypeInitializationExc

My code in Unity is only this :

> void Start () 
	{
		//Android
		AppsFlyer.setAppsFlyerKey (APPSFLYER_KEY);
		AppsFlyer.setAppID (MYPACKAGE_ID);
		AppsFlyer.loadConversionData("AppsFlyerTrackerCallbacks","didReceiveConversionData", "didReceiveConversionDataWithError");
		AppsFlyer.trackAppLaunch ();
	}

I've edited my manifest accordingly, also with needed permissions
> \<receiver android:name="com.appsflyer.MultipleInstallBroadcastReceiver" android:exported="true">
\<intent-filter>
\<action android:name="com.android.vending.INSTALL_REFERRER" />
\</intent-filter>
\</receiver>

**Comment by AppsFlyerGit** [comment]
Fixed the issue with Unity 4.x.x
