### ISSUE TITLE
AppsFlyerTrackerCallbacks prefab is broken

### ISSUE THREAD

**Issue by ekkalacheva** [AppsFlyerSDK/Unity#4]
I integrated last AppsFlyer plugin and want to use conversion data loading, but AppsFlyerTrackerCallbacks prefab is broken and can't be used.

**Comment by timmypowergamer** [comment]
Agreed. Shows up as a completely blank prefab in the inspector. You can recreate the prefab by just creating an empty GameObject named "AppsFlyerTrackerCallbacks", setting it to Static, then adding the "AppsFlyerTrackerCallbacks.cs" script to it. That might be enough to get it to work for you if you are building for Android. However, I was (and still am) unable to get the conversion data to work on iOS without major modifications to their post-process scripts. It seems the scripts are seriously broken right now, as they error out when building and don't actually make any modifications to my xcode project. Support wasn't much help, so I am still working on it...

**Comment by golan19** [comment]
Please update to the latest..there is a sample code showing how to get conversion data for both iOS & Android
