### ISSUE TITLE
Android campaign tracking

### ISSUE THREAD

**Issue by mpirate89** [AppsFlyerSDK/Unity#40]
HI! 
For campaign tracking on Android your plugin needs some Google Play Services libraries. But what exactly libraries and how to import them into UNity? 

Maybe this is solution:
https://github.com/googlesamples/unity-jar-resolver

But it requires to specify dependencies like this:
svcSupport.DependOn("com.google.android.gms", "play-services-base", "8.1+");

What are these dependencies for AppsFlyer Plugin?
Thanks!

**Comment by AppsFlyerGit** [comment]
Its not mandatory to add google play services.
