### ISSUE TITLE
Not sure what to put for android:scheme

### ISSUE THREAD

**Issue by tomatoturnip** [AppsFlyerSDK/Unity#41]
In the documentation, you specify putting your scheme in the intent-filter of the Android manifest.
```
<activity android:name="com.appsflyer.GetDeepLinkingActivity" android:exported="true">
  <intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data android:scheme="your_scheme" />
  </intent-filter>
</activity>
```
We aren't sure what to put for the scheme. (?)

**Comment by AppsFlyerGit** [comment]
Please review: https://developer.android.com/guide/topics/manifest/data-element.html
If its still unclear, please contact: support@appsflyer.com
