### ISSUE TITLE
Sample for Unity is really too simple.Don't much thing to understand and to learn!

### ISSUE THREAD

**Issue by Amobear** [AppsFlyerSDK/Unity#48]
I imported sample for Unity.I really think that it's too simple.I don't know how to use the methods to can create deep link or anything else.Document have  nothing to learn.It's also don't explains the methods use to do what.
Please Update full tutorials for Unity.

**Comment by af-golan** [comment]
please refer to: 
https://support.appsflyer.com/hc/en-us/categories/201114756-SDK-Integrations
