### ISSUE TITLE
AppsFlyerDelegate.mm registers for lifecycle events twice

### ISSUE THREAD

**Issue by neanton** [AppsFlyerSDK/Unity#53]
```
- (instancetype)init
{
    self = [super init];
    if (self) {
    
        UnityRegisterAppDelegateListener(self);
        UnityRegisterLifeCycleListener(self);
    }
    return self;
}
```

We found out that there is a call to UnityRegisterLifeCycleListener inside UnityRegisterAppDelegateListener already, so there is no need to call UnityRegisterLifeCycleListener explicitly. This causes SDK to call some methods twice (eg. didEnterBackground)

**Comment by af-dan** [comment]
Hi,

Sorry for the long response time.
We'll take a look at your proposal and make the appropriate changes if need be.

Thank you very much for your input, and please feel free to provide more insights if you have any.
