### ISSUE TITLE
Not all android devices are tracked

### ISSUE THREAD

**Issue by Firstborned** [AppsFlyerSDK/Unity#54]
Why not on all android devices are installations are tracked?
For example, installation on Samsung Galaxy S5 with android 5.1 is not tracked, but on Samsung Galaxy Tab 3 with android 4.1 or 4.2 and it's tracked.
On Android device 4.4 installation is tracked.

Only this code has been used in Unity:

```
void Start () {
        AppsFlyer.setCustomerUserID(SystemInfo.deviceUniqueIdentifier);
        //Mandatory - set your AppsFlyer’s Developer key.
        AppsFlyer.setAppsFlyerKey("%my_appsflyer_key%");
        // For detailed logging
        AppsFlyer.setIsDebug (true);

#if UNITY_IOS
        //Mandatory - set your apple app ID
        //AppsFlyer.setAppID ("%my_itunes_app_id%");
        AppsFlyer.setAppID("%my_apple_id%");
        UnityEngine.iOS.NotificationServices.RegisterForNotifications(UnityEngine.iOS.NotificationType.Alert | UnityEngine.iOS.NotificationType.Badge | UnityEngine.iOS.NotificationType.Sound);
        byte[] token = UnityEngine.iOS.NotificationServices.deviceToken;
        AppsFlyer.registerUninstall(token);
#elif UNITY_ANDROID
        //Mandatory - set your Android package name
        AppsFlyer.setAppID("%my_android_package_name%");
        //AppsFlyer.trackAppLaunch();
        AppsFlyer.setCollectIMEI(true);
        AppsFlyer.setCollectAndroidID(true);
        AppsFlyer.setGCMProjectNumber("%my_server_token%");
#endif
        AppsFlyer.trackAppLaunch();
    }
```

Android manifest:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" android:installLocation="preferExternal" android:versionCode="1" android:versionName="1.0">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <application android:theme="@style/UnityThemeSelector" android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true">
	<activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
    <activity android:name="com.facebook.unity.FBUnityLoginActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    <activity android:name="com.facebook.unity.FBUnityDialogsActivity" android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    <activity android:name="com.facebook.LoginActivity" android:configChanges="keyboardHidden|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
    <activity android:name="com.facebook.unity.FBUnityAppLinkActivity" android:exported="true" />
    <activity android:name="com.facebook.unity.FBUnityDeepLinkingActivity" android:exported="true" />
    <activity android:name="com.facebook.unity.FBUnityGameRequestActivity" />
    <activity android:name="com.facebook.unity.FBUnityCreateGameGroupActivity" />
    <activity android:name="com.facebook.unity.FBUnityJoinGameGroupActivity" />
    <activity android:name="com.facebook.unity.AppInviteDialogActivity" />
    <provider android:name="com.facebook.FacebookContentProvider" android:authorities="com.facebook.app.FacebookContentProvider301934006804678" android:exported="true" />
    <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name" android:theme="@android:style/Theme.Translucent.NoTitleBar" />
	<activity android:name="com.appsflyer.GetDeepLinkingActivity" android:exported="true">
		<intent-filter>
			<action android:name="android.intent.action.VIEW" />
			<category android:name="android.intent.category.DEFAULT" />
			<category android:name="android.intent.category.BROWSABLE" />
			<data android:scheme="sevenpinpool" />
		</intent-filter>
	</activity>
	<receiver android:name="com.appsflyer.MultipleInstallBroadcastReceiver" android:exported="true">
		<intent-filter>
			<action android:name="com.android.vending.INSTALL_REFERRER" />
		</intent-filter>
	</receiver>
	<receiver android:name="com.google.android.gms.gcm.GcmReceiver" android:exported="true">
        <intent-filter>
            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        </intent-filter>
    </receiver>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<permission android:name="com.dmd.seven.pinpool.dev.permission.C2D_MESSAGE" android:protectionLevel="signature" />
<uses-permission android:name="com.dmd.seven.pinpool.dev.permission.C2D_MESSAGE" />
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
  </application>
</manifest>`

Object with this script is placed on one scene.
Imported Appsflyer SDK 4.6.0
Also, on iOS tracking is not working.

What I'm doing wrong?

**Comment by af-dan** [comment]
Hi,

There can be various reasons for a launch to not be tracked correct, unrelated necessarily to a specific device.
Please make sure you use a Whitelisted device when testing. In addition, for Android, we recommend using our **Test App** for detailed integration testing (including Unity) - 
https://support.appsflyer.com/hc/en-us/articles/210213753-Testing-AppsFlyer-s-Android-SDK-Integration-and-Re-Targeting

For addition information and continued responsive support, please contact our Support team at **support@appsflyer.com**
