### ISSUE TITLE
Event not tracked in dashboard

### ISSUE THREAD

**Issue by hmark** [AppsFlyerSDK/Unity#57]
Hello,

I am trying to get my own dummy app working with this simple tracking code but no luck. It looks like the client notified server successfully but there is still no event tracked in the dashboard.
```
AppsFlyer.init("<MY_API_KEY>");
AppsFlyer.setAppID ("com.markhlavac.test3");

Dictionary<string, string> loginEvent = new Dictionary<string, string>();
AppsFlyer.trackRichEvent(AFInAppEvents.LOGIN, loginEvent);
```

log looks OK:
```
03-07 17:03:29.116 10522 11135 I AppsFlyer_4.6.2: ******* sendTrackingWithEvent: af_login
03-07 17:03:29.116 10522 11135 W AppsFlyer_4.6.2: Permission android.permission.ACCESS_WIFI_STATE is missing in the AndroidManifest.xml
03-07 17:03:29.124 10522 11136 I AppsFlyer_4.6.2: sendTrackingWithEvent from activity: com.unity3d.player.UnityPlayerActivity
03-07 17:03:29.124 10522 11136 I AppsFlyer_4.6.2: Trying to fetch GAID..
03-07 17:03:29.139 10522 11135 I AppsFlyer_4.6.2: IMEI was not collected.
03-07 17:03:29.141 10522 11135 I AppsFlyer_4.6.2: Android ID was not collected.
03-07 17:03:29.153 10522 11135 I AppsFlyer_4.6.2: AppsFlyer: first launch date: 2017-03-07_164209+0100
03-07 17:03:29.153 10522 11135 I AppsFlyer_4.6.2: AppsFlyerLib.sendTrackingWithEvent
03-07 17:03:29.159 10522 11135 I AppsFlyer_4.6.2: url: https://events.appsflyer.com/api/v4/androidevent?buildnumber=6.2&app_id=com.markhlavac.test3
03-07 17:03:29.159 10522 11135 I AppsFlyer_4.6.2: data: {"device":"hammerhead","firstLaunchDate":"2017-03-07_164209+0100","installDate":"2016-11-09_222858+0100","sdk":"23","referrer":"AppsFlyer_Test","reinstallCounter":"2","carrier":"Telekom SK","deviceFingerPrintId":"00000000-555a-4ce5-ffff-ffff8717ad0e","date1":"2016-11-09_222858+0100","af_preinstalled":"false","advertiserIdEnabled":"true","iaecounter":"1","lang_code":"en","appsflyerKey":"un****************eQui","app_version_name":"3.9.8","lang":"English","timepassedsincelastlaunch":"5","eventName":"af_login","advertiserId":"5998f75a-0831-4cad-b543-3ece69cfaf7d","isGaidWithGps":"true","af_v2":"ff1d4e6ed674db0bdb5b6cf7908fd17fbfbcd40d","deviceType":"user","appid":"com.markhlavac.test3","af_v":"9f43ee415ed79223cde59308442d4d651892a8de","app_version_code":"1","eventValue":"{}","af_events_api":"1","platformextension":"android_unity","network":"WIFI","operator":"Telekom SK","country":"US","date2":"2017-03-07_170305+0100","brand":"google","originalAppsflyerId":"1478726938329-8259218750548687066","af_timestamp":"1488902609116","uid":"1478726938329-4424823426779217357","isFirstCall":"false","fb":"e9c8ea75-d5db-43ea-98aa-53295230e8d4","counter":"3","model":"Nexus 5","product":"hammerhead"}
03-07 17:03:29.478 10522 11136 D AppsFlyer_4.6.2: response code: 200
```

Additional informations:
Nexus 5
Unity Pro 5.5.1p4
GooglePlay Services 0.9.36

Thanks for the help.

**Comment by af-dan** [comment]
Hi,
You need to generate a non-organic install in order to view events on your dashboard.
Please use our Test App to generate a non-organic install, and then try to trigger the in app event -
https://support.appsflyer.com/hc/en-us/articles/210213753-Testing-AppsFlyer-s-Android-SDK-Integration-and-Re-Targeting

For more information, please contact our Support team at support@appsflyer.com

**Comment by hmark** [comment]
Hi,
thanks for response but I dont understand why you closed it because the issue persists.
I whitelisted my device with AndroidID and IMEI. Your Test App finished with success but i still cant see non-organic install, nor custom event. All outputs from your application and console logs show that it should work but somehow it doesnt.
Sry, but i will not contact your support again as it is not very helpful.

**Comment by af-dan** [comment]
Hi,
As this is not a Unity-specific case (generating a non-organic install), it is our best recommendation to handle it directly with our Support team in order to provide you with the best support solutions, that is why the issue was closed.
Have you tried to contact them before?

**Comment by hmark** [comment]
Hello,
yes, i tried but their help is limited to "use our Test App" (after 7 responses), so actually they are not very helpful. It looks like my device is still not whitelisted but idk why, because your Test App finished with success and i double checked my AndroidID (generated by your Test App) and IMEI (on my device box as your Test App could not retrieved it).

**Comment by af-dan** [comment]
Can you please add your Google Advertising ID as well to the whitelist page and run the test again?
If that fails, please send me your APK so I can test it myself.
