### ISSUE TITLE
libs folder breaking Unity 5.5.2p1 due to dex formatting

### ISSUE THREAD

**Issue by littlemuggo** [AppsFlyerSDK/Unity#58]
libs folder containing play-services files and support is causing build errors for Android on Unity 5.5.2p1 due to dex formatting.

**Comment by af-dan** [comment]
Hi,
Can you share the screenshot of the build error?
What other plugins/libraries do you use in your project?

**Comment by littlemuggo** [comment]
My fault. We do have other plugins. It conflicts with (android-support-v4) which is a Google Play permissions plugin.

Full error below (replaced project path with #PROJECTPATH#. 

CommandInvokationFailure: Unable to convert classes into dex format.
/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/#PATH#/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity 5.5.2p1/PlaybackEngines/AndroidPlayer/Tools/sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorListenerCompat;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
	... 9 more
]
stdout[
processing archive /#PROJECTPATH#/Temp/StagingArea/android-libraries/GoogleAIDL/libs/./classes.jar...
processing com/android/vending/billing/BuildConfig.class...
processing com/android/vending/billing/IInAppBillingService.class...
processing com/android/vending/billing/IInAppBillingService$Stub.class...
processing com/android/vending/billing/IInAppBillingService$Stub$Proxy.class...
processing archive /#PROJECTPATH#/Temp/StagingArea/android-libraries/GooglePlay/libs/./classes.jar...
processing com/unity/purchasing/googleplay/ActivityLauncher.class...
processing com/unity/purchasing/googleplay/BillingServiceManager.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$1.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$1$2.class...
processing com/unity/purchasing/googleplay/BillingServiceManager$2.class...
processing com/unity/purchasing/googleplay/BillingServiceProcessor.class...
processing com/unity/purchasing/googleplay/BuildConfig.class...
processing com/unity/purchasing/googleplay/Consts.class...
processing com/unity/purchasing/googleplay/Consts$PurchaseState.class...
processing com/unity/purchasing/googleplay/Consts$ResponseCode.class...
processing com/unity/purchasing/googleplay/GooglePlayBillingUnAvailableException.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$1.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$2.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$3.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$4.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$5.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$6.class...
processing com/unity/purchasing/googleplay/GooglePlayPurchasing$7.class...
processing com/unity/purchasing/googleplay/IActivityLauncher.class...
processing com/unity/purchasing/googleplay/IBillingServiceManager.class...
processing com/unity/purchasing/googleplay/IabException.class...
processing com/unity/purchasing/googleplay/IabHelper.class...
processing com/unity/purchasing/googleplay/IabHelper$1.class...
processing com/unity/purchasing/googleplay/IabHelper$2.class...
processing com/unity/purchasing/googleplay/IabHelper$2$1.class...
processing com/unity/purchasing/googleplay/IabHelper$3.class...
processing com/unity/purchasing/googleplay/IabHelper$4.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnConsumeMultiFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabPurchaseFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$OnIabSetupFinishedListener.class...
processing com/unity/purchasing/googleplay/IabHelper$QueryInventoryFinishedListener.class...
processing com/unity/purchasing/googleplay/IabResult.class...
processing com/unity/purchasing/googleplay/Inventory.class...
processing com/unity/purchasing/googleplay/Purchase.class...
processing com/unity/purchasing/googleplay/PurchaseActivity.class...
processing com/unity/purchasing/googleplay/PurchaseFailedEvent.class...
processing com/unity/purchasing/googleplay/SkuDetails.class...
processing archive /#PROJECTPATH#/Temp/StagingArea/android-libraries/UnityOBBDownloader/bin/obfuscated_googleplaydownloader.jar...
processing com/unity3d/plugin/downloader/UnityAlarmReceiver.class...
processing com/unity3d/plugin/downloader/UnityDownloaderActivity.class...
processing com/unity3d/plugin/downloader/UnityDownloaderService.class...
processing com/unity3d/plugin/downloader/a.class...
processing com/unity3d/plugin/downloader/a/a.class...
processing com/unity3d/plugin/downloader/a/b.class...
processing com/unity3d/plugin/downloader/a/c.class...
processing com/unity3d/plugin/downloader/a/d.class...
processing com/unity3d/plugin/downloader/a/e.class...
processing com/unity3d/plugin/downloader/a/f.class...
processing com/unity3d/plugin/downloader/a/g.class...
processing com/unity3d/plugin/downloader/a/h.class...
processing com/unity3d/plugin/downloader/a/i.class...
processing com/unity3d/plugin/downloader/a/j.class...
processing com/unity3d/plugin/downloader/a/k.class...
processing com/unity3d/plugin/downloader/a/l.class...
processing com/unity3d/plugin/downloader/a/m.class...
processing com/unity3d/plugin/downloader/a/n.class...
processing com/unity3d/plugin/downloader/a/o.class...
processing com/unity3d/plugin/downloader/a/p.class...
processing com/unity3d/plugin/downloader/b.class...
processing com/unity3d/plugin/downloader/b/a.class...
processing com/unity3d/plugin/downloader/b/b.class...
processing com/unity3d/plugin/downloader/b/c.class...
processing com/unity3d/plugin/downloader/b/d.class...
processing com/unity3d/plugin/downloader/b/e.class...
processing com/unity3d/plugin/downloader/b/f.class...
processing com/unity3d/plugin/downloader/b/g.class...
processing com/unity3d/plugin/downloader/b/h.class...
processing com/unity3d/plugin/downloader/b/i.class...
processing com/unity3d/plugin/downloader/b/j.class...
processing com/unity3d/plugin/downloader/b/k.class...
processing com/unity3d/plugin/downloader/b/l.class...
processing com/unity3d/plugin/downloader/b/m.class...
processing com/unity3d/plugin/downloader/b/n.class...
processing com/unity3d/plugin/downloader/b/o.class...
processing com/unity3d/plugin/downloader/b/p.class...
processing com/unity3d/plugin/downloader/b/q.class...
processing com/unity3d/plugin/downloader/b/r.class...
processing com/unity3d/plugin/downloader/b/s.class...
processing com/unity3d/plugin/downloader/b/t.class...
processing com/unity3d/plugin/downloader/b/u.class...
processing com/unity3d/plugin/downloader/b/v.class...
processing com/unity3d/plugin/downloader/b/w.class...
processing com/unity3d/plugin/downloader/b/x.class...
processing com/unity3d/plugin/downloader/b/y.class...
processing com/unity3d/plugin/downloader/b/z.class...
processing com/unity3d/plugin/downloader/c.class...
processing com/unity3d/plugin/downloader/c/a.class...
processing com/unity3d/plugin/downloader/c/b.class...
processing com/unity3d/plugin/downloader/c/c.class...
processing com/unity3d/plugin/downloader/c/d.class...
processing com/unity3d/plugin/downloader/c/e.class...
processing com/unity3d/plugin/downloader/c/f.class...
processing com/unity3d/plugin/downloader/c/g.class...
processing com/unity3d/plugin/downloader/c/h.class...
processing com/unity3d/plugin/downloader/c/i.class...
processing com/unity3d/plugin/downloader/c/j.class...
processing com/unity3d/plugin/downloader/c/k.class...
processing com/unity3d/plugin/downloader/c/l.class...
processing com/unity3d/plugin/downloader/c/m.class...
processing com/unity3d/plugin/downloader/c/n.class...
processing com/unity3d/plugin/downloader/c/o.class...
processing com/unity3d/plugin/downloader/c/p.class...
processing com/unity3d/plugin/downloader/c/q.class...
processing com/unity3d/plugin/downloader/c/r.class...
processing com/unity3d/plugin/downloader/c/s.class...
processing com/unity3d/plugin/downloader/c/t.class...
processing com/unity3d/plugin/downloader/c/u.class...
processing com/unity3d/plugin/downloader/d/a.class...
processing com/unity3d/plugin/downloader/d/b.class...
processing archive /#PROJECTPATH#/Temp/StagingArea/android-libraries/common/libs/./classes.jar...
processing com/unity/purchasing/BuildConfig.class...
processing com/unity/purchasing/common/DelayedHandler.class...
processing com/unity/purchasing/common/IDelayedExecutor.class...
processing com/unity/purchasing/common/INativeStore.class...
processing com/unity/purchasing/common/IStore.class...
processing com/unity/purchasing/common/IStoreCallback.class...
processing com/unity/purchasing/common/IUnityCallback.class...
processing com/unity/purchasing/common/InitializationFailureReason.class...
processing com/unity/purchasing/common/ProductDefinition.class...
processing com/unity/purchasing/common/ProductDescription.class...
processing com/unity/purchasing/common/ProductMetadata.class...
processing com/unity/purchasing/common/ProductType.class...
processing com/unity/purchasing/common/PurchaseFailedEvent.class...
processing com/unity/purchasing/common/PurchaseFailureDescription.class...
processing com/unity/purchasing/common/PurchaseFailureReason.class...
processing com/unity/purchasing/common/SaneJSONObject.class...
processing com/unity/purchasing/common/StoreDeserializer.class...
processing com/unity/purchasing/common/UnityPurchasing.class...
processing archive /Users/#PROJECTPATH#/Temp/StagingArea/android-libraries/play-services-base-9.6.1/libs/./classes.jar...
ignored resource META-INF/
ignored resource META-INF/MANIFEST.MF
ignored resource com/
ignored resource com/google/
ignored resource com/google/android/
ignored resource com/google/android/gms/
ignored resource com/google/android/gms/auth/
ignored resource com/google/android/gms/auth/api/
ignored resource com/google/android/gms/auth/api/signin/
processing com/google/android/gms/auth/api/signin/GoogleSignInAccount.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInAccount$1.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInOptions.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInOptions$1.class...
processing com/google/android/gms/auth/api/signin/GoogleSignInOptions$Builder.class...
ignored resource com/google/android/gms/auth/api/signin/internal/
processing com/google/android/gms/auth/api/signin/internal/zze.class...
processing com/google/android/gms/auth/api/signin/internal/zzk.class...
processing com/google/android/gms/auth/api/signin/zza.class...
processing com/google/android/gms/auth/api/signin/zzb.class...
ignored resource com/google/android/gms/common/
processing com/google/android/gms/common/ErrorDialogFragment.class...
processing com/google/android/gms/common/GoogleApiAvailability.class...
processing com/google/android/gms/common/GooglePlayServicesUtil.class...
processing com/google/android/gms/common/GooglePlayServicesUtil$zza.class...
processing com/google/android/gms/common/SignInButton.class...
processing com/google/android/gms/common/SignInButton$ButtonSize.class...
processing com/google/android/gms/common/SignInButton$ColorScheme.class...
processing com/google/android/gms/common/SupportErrorDialogFragment.class...
ignored resource com/google/android/gms/common/api/
processing com/google/android/gms/common/api/Api.class...
processing com/google/android/gms/common/api/Api$ApiOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$HasOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$NoOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$NotRequiredOptions.class...
processing com/google/android/gms/common/api/Api$ApiOptions$Optional.class...
processing com/google/android/gms/common/api/Api$zza.class...
processing com/google/android/gms/common/api/Api$zzb.class...
processing com/google/android/gms/common/api/Api$zzc.class...
processing com/google/android/gms/common/api/Api$zzd.class...
processing com/google/android/gms/common/api/Api$zze.class...
processing com/google/android/gms/common/api/Api$zzf.class...
processing com/google/android/gms/common/api/Api$zzg.class...
processing com/google/android/gms/common/api/Api$zzh.class...
processing com/google/android/gms/common/api/Api$zzi.class...
processing com/google/android/gms/common/api/Batch.class...
processing com/google/android/gms/common/api/Batch$1.class...
processing com/google/android/gms/common/api/Batch$Builder.class...
processing com/google/android/gms/common/api/BatchResult.class...
processing com/google/android/gms/common/api/BatchResultToken.class...
processing com/google/android/gms/common/api/BooleanResult.class...
processing com/google/android/gms/common/api/GoogleApiActivity.class...
processing com/google/android/gms/common/api/GoogleApiClient.class...
processing com/google/android/gms/common/api/GoogleApiClient$Builder.class...
processing com/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks.class...
processing com/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener.class...
processing com/google/android/gms/common/api/OptionalPendingResult.class...
processing com/google/android/gms/common/api/PendingResult.class...
processing com/google/android/gms/common/api/PendingResult$zza.class...
processing com/google/android/gms/common/api/PendingResults.class...
processing com/google/android/gms/common/api/PendingResults$zza.class...
processing com/google/android/gms/common/api/PendingResults$zzb.class...
processing com/google/android/gms/common/api/PendingResults$zzc.class...
processing com/google/android/gms/common/api/ResultTransform.class...
processing com/google/android/gms/common/api/TransformedResult.class...
processing com/google/android/gms/common/api/zzb.class...
processing com/google/android/gms/common/api/zzc.class...
processing com/google/android/gms/common/api/zzd.class...
processing com/google/android/gms/common/api/zzf.class...
ignored resource com/google/android/gms/common/data/
processing com/google/android/gms/common/data/AbstractDataBuffer.class...
processin<message truncated>

**Comment by af-dan** [comment]
If you already have the support library imported from another plugin, please try removing it from the libs folder and see if the problem pesists

**Comment by littlemuggo** [comment]
Resolved.
