### ISSUE TITLE
iOS Push notification

### ISSUE THREAD

**Issue by ikitae** [AppsFlyerSDK/Unity#59]
Hello,

I'm using OneSignal Push service.
iOS Can't get push notification token after integrate AppsFlyer.

I put 2 method on 'AppsFlyerAppController.m '
And it solved.
Please check this issue.

### Solution ###
- (void)application:(UIApplication*)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData*)deviceToken
{
    [super application:application didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication*)application didFailToRegisterForRemoteNotificationsWithError:(NSError*)error
{
    [super application:application didFailToRegisterForRemoteNotificationsWithError:error];
}

**Comment by af-fess** [comment]
@ikitae hi,  please open pull request

Thanks,

**Comment by ikitae** [comment]
I have no permission to send pull request.
