### ISSUE TITLE
init(key) called twice on Android

### ISSUE THREAD

**Issue by boerjesieling** [AppsFlyerSDK/Unity#65]
Hi, according to your documentation for unity / android setAppsFlyerKey(key) should be called, and after that init(key). By taking a look in the source code (AppsFlyer.cs) it turned out that setAppsFlyerKey just calls the init(..) method. This would result in 2 calls of the init method. I dont think, this is intended. (It seems to have an effect on the re-targeting by tracking 2 re-attributions or re-engagements instead of 1)

**Comment by af-fess** [comment]
fixed in 4.14.3
