### ISSUE TITLE
Crash on IOS when trying to launch application second Time

### ISSUE THREAD

**Issue by moloshniy** [AppsFlyerSDK/Unity#8]
When launch first time  Everything is ok. But on second  time i got  an exception in xCode 

UIApplicationMain(argc, argv, nil, [NSString stringWithUTF8String:AppControllerClassName]); 
(EXC_BAD_ACCESS )
Some times another  exception.

I used  your test scene. FIX PLIZ!

**Comment by golan19** [comment]
Fixed..

**Comment by mrpacogp** [comment]
What are the problem? i got the same...
